name: Webcomic
description: Pravin's Webcomic
url: https://jfenn.me/webcomic_test
baseurl: "/"

collections:
    comics:
        output: true
        permalink: /comics/:title/
    pages:
        output: true
        permalink: /:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

sass:
    sass_dir: ./css
