name: The Newspanels
description: Pravin's Webcomic
url: https://jfenn.me/webcomic_test
baseurl: "/"

collections:
    comics:
        output: true
        permalink: comics/:slug/
    pages:
        output: true
        permalink: :slug/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

sass:
    sass_dir: ./css
